WITH TEMP AS (
    SELECT 
        CART_ID,
        IF(NAME = 'Yogurt', 1, 0) AS IS_YOGURT,
        IF(NAME = 'Milk', 1, 0) AS IS_MILK
    FROM CART_PRODUCTS
)

SELECT CART_ID
FROM TEMP
GROUP BY CART_ID
HAVING SUM(IS_YOGURT) > 0 AND SUM(IS_MILK) > 0
ORDER BY CART_ID