SELECT A.ANIMAL_ID, A.NAME
FROM (
    SELECT AINS.ANIMAL_ID, AINS.NAME, DATEDIFF(AOUT.DATETIME, AINS.DATETIME) AS DATE_GAP
    FROM ANIMAL_INS AINS
    JOIN ANIMAL_OUTS AOUT
    ON AINS.ANIMAL_ID = AOUT.ANIMAL_ID
    ORDER BY DATE_GAP DESC
    LIMIT 2
) AS A
