SELECT 
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
WHERE (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
    AND C.DURATION_TYPE = '30일 이상'
    AND NOT EXISTS (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE A.CAR_ID = B.CAR_ID
        AND (B.START_DATE <= '2022-11-30' AND B.END_DATE >= '2022-11-01')
    )
    AND 500000 <= FLOOR(A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30)
    AND FLOOR(A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;