SELECT
    RANKED.ID,
    CASE
        WHEN RANKED.RNK <= RANKED.CNT * (1 / 4) THEN  'CRITICAL'
        WHEN RANKED.RNK <= RANKED.CNT * (2 / 4) THEN  'HIGH'
        WHEN RANKED.RNK <= RANKED.CNT * (3 / 4) THEN  'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME

FROM (
    SELECT ID,
        ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RNK,
        COUNT(*) OVER () AS CNT
    FROM ECOLI_DATA
) AS RANKED
ORDER BY RANKED.ID ASC;

