WITH S AS (
SELECT
    REST_ID,
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW  
GROUP BY REST_ID
)

SELECT
    RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    S.SCORE
FROM REST_INFO RI
JOIN S
ON RI.REST_ID = S.REST_ID
WHERE ADDRESS LIKE "서울%"
ORDER BY S.SCORE DESC, RI.FAVORITES DESC;

