WITH RECURSIVE RESULT AS (
    SELECT
        1 AS GENERATION,
        ID,
        PARENT_ID
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    UNION
    
    SELECT 
        GENERATION + 1, ECOLI_DATA.ID, ECOLI_DATA.PARENT_ID
    FROM ECOLI_DATA
    JOIN RESULT
    ON ECOLI_DATA.PARENT_ID = RESULT.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM RESULT
WHERE ID NOT IN (SELECT IFNULL(PARENT_ID,-1) FROM RESULT)
GROUP BY GENERATION
ORDER BY GENERATION
