WITH T AS (
    SELECT 
        A.HISTORY_ID,
        B.DAILY_FEE,
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS DAY,
        CASE
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(A.END_DATE, A.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'None'
        END AS PER
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN CAR_RENTAL_COMPANY_CAR B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
)

SELECT
    T.HISTORY_ID,
    ROUND(T.DAILY_FEE * (1 - (IFNULL(C.DISCOUNT_RATE, 0) / 100)) * T.DAY, 0) AS FEE
FROM T
LEFT JOIN (
    SELECT 
        DURATION_TYPE,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭'
) AS C
ON T.PER = C.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;