WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H + 1 
    FROM HOURS
    WHERE H < 23
)
SELECT 
    HOURS.H AS HOUR,
    COALESCE(T.CNT, 0) AS COUNT
FROM HOURS
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR_VAL, COUNT(*) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR_VAL
) T
    ON HOURS.H = T.HOUR_VAL
ORDER BY HOURS.H;