SET @X = -1;
WITH ALLTIME AS (
    
    SELECT (@X := @X + 1) AS HOUR, 0 AS COUNT
    FROM ANIMAL_OUTS 
    WHERE @X < 23
    UNION
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY HOUR(DATETIME)
)
SELECT HOUR, SUM(COUNT) AS COUNT
FROM ALLTIME
GROUP BY HOUR
ORDER BY HOUR
