WITH H AS (
    SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME, S.CATEGORY
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON (D.SKILL_CODE & S.CODE) > 0
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM H
WHERE CATEGORY = 'Front End'
ORDER BY ID ASC;