WITH H AS (
    SELECT D.ID, S.CATEGORY
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON (D.SKILL_CODE & S.CODE) > 0
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D
WHERE 'Front End' IN (SELECT CATEGORY FROM H WHERE H.ID = D.ID)
ORDER BY ID ASC;