# 사람이름과 글쓴 수를 정리
WITH CNT AS (
    SELECT MP.MEMBER_NAME, COUNT(*) AS C
    FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
    GROUP BY MP.MEMBER_NAME
),
# 글을 가장 많이 쓴 사람의 리스트
BEST AS (
    SELECT MEMBER_NAME
    FROM CNT
    WHERE C = (
        SELECT COUNT(*)
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ORDER BY COUNT(*) DESC
        LIMIT 1
    )
)

SELECT 
    MP.MEMBER_NAME, 
    RR.REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_NAME IN (SELECT * FROM BEST)
ORDER BY REVIEW_DATE, RR.REVIEW_TEXT